### ISSUE TITLE
explanation about odom_fix

### ISSUE THREAD

**Issue by germal** [Enmar123/rs_odom_fix#1]
Hello Jason,

I found your node on github , because I am trying to convert base_link of my robot to t265 pose frame.
Furthermore I need to fuse  the two odometries ( wheel and t265 )  before to feed rtabmap.
I think that it should be done with robot localization node , but how should I  modify the parameters in your tf_to_odom_v6.py  ?

    odom_sub = rospy.Subscriber("/t265/odom/sample", Odometry, callback)
    odom_pub = rospy.Publisher("?", Odometry , queue_size=10)
    odom_msg.header.frame_id = "ekf_odom"
    odom_msg.child_frame_id = "?
   listener.lookupTransform('t265_pose_frame', 'fake_base_link', rospy.Time(0))"

This is my graph 

![image](https://user-images.githubusercontent.com/47027729/94371822-9ca75200-00f9-11eb-993f-46beab0c6635.png)

Thanks in advance !
germal

**Comment by Enmar123** [comment]
First let me explain how this node works a bit more clearly, this was a quick fix and I never cleaned it up or really documented it! What we are doing is creating a fake transform from the camera back to the "origin" of the robot (the point around which your robot rotates and translates, typically where your base_link frame is). We then take the position of the endpoint of that transform and convert it into an odometry message that appears to originate from the main robot. 

Assuming the xyz transform translation from the origin of your robot to your camera is (1, 0, 0.5) then in "tf_broadcaster.py" you should set the translation components to (-1, 0 ,-0.5) since we are transforming *back* to the origin. 

I also had a bit of an odd config for my robot so you will likely want to change the following in "tf_to_odom_v6.py"
odom_msg.header.frame_id = "odom"
odom_msg.child_frame_id = "base_link"

Try this and see if you don't get a usable odometry out of "tf_to_odom_v6.py."

**Comment by germal** [comment]
Hello @Enmar123 thank you for your explanation !
So this is useful only in case  I would fuse t265 odom with wheeel odom with an ekf ? If I would use only t265 odom ,would be enough only a static tf transform between base link and and t265 pose frame to join the trees ( camera tree and robot tree ) ?

**Comment by Enmar123** [comment]
This pkg is useful If you want to us the rst265 as your single source of odometry, but its primarily for making it compatible with sensor fusion using the robot_localization pkg. The rst265 kinda wants to take over your tf_tree and be the center of everything, which is a pain if you have other components on your robot or want to keep your existing tree structure. You don't need this if you will only be using the rst265.

**Comment by germal** [comment]
You are right t265 is a little egocentric  !
Could you share also the robot localization configuration for t265 and other odometry ?

**Comment by Enmar123** [comment]
Unfortunately I don't have access to the config files atm. They are also pretty robot dependent so you are probably better off setting them up based on your robot. Take a look at this link, it describes what each of the configuration parameters does. [http://docs.ros.org/melodic/api/robot_localization/html/configuring_robot_localization.html](url)

**Comment by germal** [comment]
Thank you for all Jason ,now I have a clearer understanding of t265  usage and characteristics !
Cheers
germal
